import React, { Component } from "react";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Col, Row, Nav, Container } from 'react-bootstrap';
import Script from 'next/script';

const artData =[
  {"title":"Brynhildr", "thumb":"brynhildr-thumb.jpg", "fullImage":"brynhildr.jpg", "description":""},
  {"title":"Hope", "thumb":"hope-thumb.jpg", "fullImage":"hope.jpg", "description":""},
  {"title":"Ursulla, the Portal Caster", "thumb":"ursula-thumb.png", "fullImage":"ursula.jpg", "description":""},
  {"title":"Sea Sentinel", "thumb":"sea-sentinel-thumb.jpg", "fullImage":"sea-sentinel.jpg", "description":""},
  {"title":"Bharkatar, the Worm King", "thumb":"bharkatar-thumb.jpg", "fullImage":"bharkatar.jpg", "description":""},
  {"title":"Plaits", "thumb":"plaits-thumb.jpg", "fullImage":"plaits.png", "description":""},
  {"title":"Apothecary", "thumb":"apothecary-thumb.png", "fullImage":"apothecary.png", "description":""},
  {"title":"Blood Vassal", "thumb":"blood-vassal-thumb.jpg", "fullImage":"blood-vassal.jpg", "description":""},
]


class Home extends Component {
  constructor(props) {
    super(props);

    this.state = {
      isMobileMenuOpen: false,
      isContactOpen: false,
      lightBox:"",
    };
  }



  render() {
    return (
      <div>
                  <Script src="https://kit.fontawesome.com/42934578f1.js"></Script>

        <Head>
          <title>Bruno Formagio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <meta charset="utf-8" />
          <meta name="description" content="Art Portfolio of Bruno Formagio" />
          <meta name="keywords" content="Art,Arte,2D,Portfólio,Portfolio,Concept,Illustrator,Illustration,Ilustração,Ilustrador,Artista,Artist,Brazilian Artist,Artista Gramadense,Bruno Formagio,Formaggio,Formagio,Artes Visuais" />
          <meta name="author" content="Bruno Formagio" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png" />
          <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png" />
          <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png" />
          <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png" />
          <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png" />
          <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png" />
          <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png" />
          <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png" />
          <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png" />
          <link rel="icon" type="image/png" sizes="192x192" href="/android-icon-192x192.png" />
          <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
          <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png" />
          <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
          <link rel="manifest" href="/manifest.json" />
          <meta name="msapplication-TileColor" content="#000000" />
          <meta name="msapplication-TileImage" content="/ms-icon-144x144.png" />
          <meta name="theme-color" content="#000000" />
          <meta property="og:image" content="/facethumb.jpg" />
        </Head>

        {this.state.lightBox !== "" && <div className={styles.lightBox}>
          <img src={"/portfolio/"+this.state.lightBox} alt={this.state.lightBox}/>
          <div onClick={()=> this.setState({lightBox:""})}>&#x2715;</div>
          </div>}

        <header className={styles.headerHome}>
        <div className={styles.logoArea}>
                  <img src={"/logo.svg"} alt="Logo" className={styles.logoMobile}/>
                  <img src={"/logo-extra.svg"} alt="Bruno Formagio"  className={styles.logoDesktop} />
                  </div>

                  <div className={styles.contactArea}>
                    <a href="http://instagram.com/artofbrunoformagio" target={"_blank"} rel="noreferrer"><i className="fab fa-instagram"></i></a>
                    <a href="https://www.artstation.com/brunoformagio" target={"_blank"} rel="noreferrer"><i className="fab fa-artstation"></i></a>
                    <a href="mailto:contato@brunoformagio.com.br" target={"_blank"} rel="noreferrer"><i className="fa fa-envelope"></i></a>
                  </div>


        </header>


        <main className={styles.main}>
        {artData.map((a,i) => 
        <div key={i} className={styles.artThumb} onClick={() => this.setState({lightBox:a.fullImage})} style={{backgroundImage:`url(/portfolio/${a.thumb})`}}>
          <div className={styles.desc}>
            <h2>&ldquo;{a.title}&rdquo;</h2>
          </div>

        </div>)}
        </main>

        <footer className={styles.footer}>
          Bruno Formagio © 2022. All Rights Reserved.
        </footer>
      </div>
    )
  }
}

export default Home;
